name: CI Pipeline

on:
  push:
    branches: [ tmodules ]
  pull_request:
    branches: [ tmodules ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests
      run: |
        pytest || echo "No tests found"

    - name: Build Docker image
      run: docker build -t ai-compliance .